#!/usr/bin/python -ttu
# -*- coding: utf-8 -*-

# Chicken automatic door controller.
# - automatically actuates chicken door based on light level
# - takes photo, sends to Imgur album https://imgur.com/a/7eKFl
# - sends notifications to Slack channel https://chxhq.slack.com/messages/C6DL0SR16/
#
# Prerequisites
# - Python 2.7
# - sudo pip install imgurpython

# autodoor
# Copyright (C) 2018 Adam Monsen
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import datetime
import json
import os

import chxlib

lightLevel = chxlib.getLightLevel()
doorState = chxlib.getDoorState()

chxlib.log('📊 Light level {}, door is {}.'.format(lightLevel, doorState), level='DEBUG')

dooracle = chxlib.doorOracle(lightLevel=lightLevel, doorState=doorState)

if dooracle['recommend'] != 'none':
    chxlib.log(dooracle['message'], level=dooracle['severity'])
    chxlib.door(dooracle['recommend'], doorState=doorState)
    # Take a photo and start or stop motion. We can't take a photo while motion
    # is running.
    if dooracle['recommend'] == 'open':
        chxlib.postPhoto(chxlib.takePhoto())
        chxlib.systemctl(unit='motion', action='start')
        chxlib.log('☄ Initiated motion detection', level='DEBUG')
    elif dooracle['recommend'] == 'close':
        chxlib.systemctl(unit='motion', action='stop')
        chxlib.log('☄ Terminated motion detection', level='DEBUG')
        chxlib.postPhoto(chxlib.takePhoto())
