#!/usr/bin/python -ttu
# -*- coding: utf-8 -*-

# door - opens/closes chicken door
# Copyright (C) 2018 Adam Monsen
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import chxlib

def get_args():
    import argparse
    parser = argparse.ArgumentParser(description='Open or close door. Ctrl-c aborts.')
    parser.add_argument('cmd', type=str, choices=['open','close'])
    return parser.parse_args()

if __name__ == '__main__':
    args = get_args()
    chxlib.log('✋ Manual door {} request.'.format(args.cmd))
    chxlib.door(args.cmd)
