#!/usr/bin/python -ttu
# -*- coding: utf-8 -*-

# imgur-upload - upload image to imgur
# Copyright (C) 2018 Adam Monsen
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import chxlib

def get_args():
    import argparse
    parser = argparse.ArgumentParser(description='Upload image to imgur and write log message.')
    parser.add_argument('file', type=argparse.FileType('r'))
    return parser.parse_args()

if __name__ == '__main__':
    args = get_args()
    args.file.close() # because argparse opens it
    chxlib.postPhoto(args.file.name)
