#!/usr/bin/python -ttu
# -*- coding: utf-8 -*-

# Check if uploaded YouTube videos have thumbnails yet and if so, post them to Slack

# youtube-flush
# Copyright (C) 2018 Adam Monsen
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import os
import requests
import time

import chxlib

for path, dirs, files in os.walk(chxlib.youtubeIdsDir):
    youtubeIds = files

one_minute = 60 # seconds
ten_minutes = one_minute * 10

for youtubeId in youtubeIds:
    filename = os.path.join(chxlib.youtubeIdsDir, youtubeId)
    s = os.stat(filename)
    if time.time() - s.st_mtime > ten_minutes:
        # Abort stale & likely failed YouTube uploads.
        #
        # Some uploads get stuck in "95% complete" or something. Ignore them.
        # They'll be more chicken activity later.
        #
        # Maybe this happens with invalid video files.
        chxlib.log('🧀 youtubeId {} is very stale and likely failed. Aborting.'.format(youtubeId), level='DEBUG')
        os.unlink(filename)
        continue
    thumbnailUrl = 'https://img.youtube.com/vi/{}/0.jpg'.format(youtubeId)
    r = requests.head(thumbnailUrl)
    if r.status_code == 200:
        # post YouTube video link to Slack - Slack should unfurl since thumbnail now exists
        videoUrl = 'https://www.youtube.com/watch?v={}'.format(youtubeId)
        chxlib.log('📺 Coop activity: {}'.format(videoUrl), level='DEBUG')
        # delete youtubeId file
        os.unlink(filename)
    elif r.status_code == 404:
        chxlib.log('👀 No thumbnail yet for youtubeId {}'.format(youtubeId), level='DEBUG')
    else:
        message = '🙈 Unexpected HTTP response code {} for HEAD {}'.format(r.status_code, thumbnailUrl)
        chxlib.log(message, level='DEBUG')
