#!/bin/bash

# Wrap Python YouTube upload script from
# https://github.com/youtube/api-samples/blob/master/python/upload_video.py .
# Created because I don't want to miss any status or error messages and I'm not
# sure I captured all the places the Python upload script will or might output
# and I don't know how motion calls the on_movie_end script (can I use args?).
# And that was a really long run-on sentence.

# youtube-upload
# Copyright (C) 2018 Adam Monsen
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -o errexit
set -o nounset
set -o pipefail

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

cd "$DIR/../Chicken/lib"

python -ttu youtube-upload.py --file "$1" 2>&1 | logger -t youtube-upload
